version: '3.4'
services:
  nginx:
    build: ./nginx
    image: 127.0.0.1:5000/nginx
    ports:
      - "80:80"
    networks:
      - web
    restart: always
  php:
    build: ./nginx
    image: 127.0.0.1:5000/php
    networks:
      - web
    restart: always
networks:
  web:
    driver: overlay

